---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: grafana-admins
spec:
  friendlyName: Grafana Admins
  name: grafana_admins
  users:
    usernames:
      - cburnham
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: grafana-users
spec:
  friendlyName: Grafana
  name: grafana_users
  users:
    usernames:
      - cburnham
      - jburnham
