---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
spec:
  endpoints:
    - port: grafana
      path: /metrics
      honorLabels: true
  jobLabel: grafana
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      dashboards: grafana
