---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-certificates
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
  interval: 30m
  path: ./kubernetes/apps/network/ingress-nginx/certificates
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: area0
  timeout: 3m
  wait: true
