---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  dataFrom:
    - extract:
        key: cluster-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cluster-secrets
    template:
      data:
        # global
        CLUSTER_TIME_ZONE: "{{ .CLUSTER_TIME_ZONE }}"
        SECRET_DOMAIN: "{{ .EXTERNAL_DOMAIN }}"

        # networks
        NET_HOME_CIDR: "{{ .NET_HOME_CIDR }}"

        # service addresses
        SVC_GATEWAY_EXTERNAL: "{{ .SVC_GATEWAY_EXTERNAL }}"
        SVC_GATEWAY_INTERNAL: "{{ .SVC_GATEWAY_INTERNAL }}"
        SVC_K8S_GATEWAY: "{{ .SVC_K8S_GATEWAY }}"
        SVC_PLEX: "{{ .SVC_PLEX }}"
        SVC_CNPG_CLUSTER: "{{ .SVC_CNPG_CLUSTER }}"
        SVC_SPLUNK: "{{ .SVC_SPLUNK }}"
        SVC_CRIBL_LEADER: "{{ .SVC_CRIBL_LEADER }}"
        SVC_CRIBL_WORKER: "{{ .SVC_CRIBL_WORKER }}"
        SVC_TAILSCALE: "{{ .SVC_TAILSCALE }}"

        # site addresses
        HOME_ASSISTANT_ADDRESS: "{{ .HOME_ASSISTANT_ADDRESS }}"
        MINIO_ADDRESS: "{{ .MINIO_ADDRESS }}"
        NAS_ADDRESS: "{{ .NAS_ADDRESS }}"

        # nfs
        NFS_DATA_PATH: "{{ .NFS_DATA_PATH }}"
        NFS_SHARED_PATH: "{{ .NFS_SHARED_PATH }}"
