---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
commonLabels:
  app.kubernetes.io/instance: &app frigate
  app.kubernetes.io/name: *app
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./config
