---
nameOverride: &app sonarr
env:
  SONARR__INSTANCE_NAME: Sonarr
  SONARR__LOG_LEVEL: info
  SONARR__PORT: &port 8989
envFrom:
  - secretRef:
      name: *app
image:
  repository: ghcr.io/onedr0p/sonarr-develop
  tag: 4.0.0.397@sha256:c4e924f3c0305f63945550aa2318f559de56a40fdad6d88d60edd097672aa996
ingress:
  main:
    annotations:
      hajimari.io/group: Media
      hajimari.io/icon: mdi:television-classic
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Accept-Encoding "";
        sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/sonarr/dark.css"></head>';
        sub_filter_once on;
    enabled: true
    hosts:
      - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    ingressClassName: nginx
    tls:
      - hosts:
          - *host
nodeSelector:
  node-role.kubernetes.io/media: "true"
persistence:
  backup:
    enabled: true
    mountPath: /config/Backups
    path: "${NAS_NFS_PATH}/backup/app/sonarr"
    server: "${NAS_ADDRESS}"
    type: nfs
  config:
    enabled: true
    existingClaim: sonarr-config-v1
  media:
    enabled: true
    mountPath: /media
    path: "${MEDIA_SERVER_NFS_PATH}"
    server: "${MEDIA_SERVER_ADDRESS}"
    type: nfs
podAnnotations:
  secret.reloader.stakater.com/reload: *app
podSecurityContext:
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  runAsGroup: 568
  runAsUser: 568
  supplementalGroups:
    - 100
service:
  main:
    ports:
      http:
        port: *port
