# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   defaults/main.yml
#   @description    :   defaults for ansible-role-os
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
# --------------------------------------------------------------------------------------------------
# disk settings
# --------------------------------------------------------------------------------------------------
# -- (str) smartd config
os_smartd_config: "DEVICESCAN -a -o on -S on -n standby,q -s (L/../../6/03|S/../.././02) -W 4,35,40 -m root"
# ==================================================================================================

# --------------------------------------------------------------------------------------------------
# operating system packages
# --------------------------------------------------------------------------------------------------
# -- (dict) operating system packages
os_packages:

  # -- (dict) operating system family
  debian:

    # -- (list) flat list of packages to be installed with apt
    apt_install:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - htop
      - nano
      - nfs-common
      - ntpdate
      - psmisc
      - python
      - python3
      - python3-apt
      - python3-reportbug
      - python3-software-properties
      - software-properties-common
      - sudo
      - unattended-upgrades
      - unzip

    # -- (list) flat list of packages to be uninstalled with apt
    apt_remove:
      - bcache-tools
      - btrfs-progs
      - fwupd
      - open-vm-tools
      - tmux
# ==================================================================================================

# --------------------------------------------------------------------------------------------------
# reboot settings
# --------------------------------------------------------------------------------------------------
# -- (bool) reboot host if needed
os_reboot_if_needed: "{{ reboot_if_needed | default(true) }}"
# ==================================================================================================

# --------------------------------------------------------------------------------------------------
# time settings
# --------------------------------------------------------------------------------------------------
# -- (str) timezone for the os
os_timezone: "{{ timezone | default('America/Chicago') }}"

# -- (bool) use ntp
os_ntp_enabled: true

# -- (dict) ntp servers
os_ntp_servers:
  # -- (list) flat list of primary ntp servers
  primary:
    - "time.cloudflare.com"
    - "time.google.com"

  # -- (list) flat list of secondary ntp servers
  fallback:
    - "0.us.pool.ntp.org"
    - "1.us.pool.ntp.org"
    - "2.us.pool.ntp.org"
    - "3.us.pool.ntp.org"
# ==================================================================================================
