# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   tasks/Debian/sysctl.yml
#   @description    :   Debian sysctl tasks
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
- name: "{{ ansible_os_family }} | sysctl | set kubernetes sysctl configuration"
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    reload: true
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    value: "{{ item.value }}"
  with_dict: "{{ sysctl_config }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.bridge.bridge-nf-call-iptables: 1
      net.bridge.bridge-nf-call-ip6tables: 1
      net.ipv4.conf.default.rp_filter: 0
      net.ipv4.conf.all.rp_filter: 0
      fs.inotify.max_user_watches: 524288
      fs.inotify.max_user_instances: 512
