---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./crul
  - ./home-assistant
  - ./minio
  - ./pi-hole
  - ./protect
  - ./s3
  - ./synology-dsm
  - ./synology-files
  - ./synology-photos
  - ./unifi
