---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &name "${SECRET_DOMAIN/./-}-tls"
spec:
  data:
    - match:
        remoteRef:
          property: &key tls.crt
          remoteKey: *name
        secretKey: *key
    - match:
        remoteRef:
          property: &key tls.key
          remoteKey: *name
        secretKey: *key
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: *name
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
