---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-reloader
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: reloader
      namespace: kube-system
  interval: 30m
  path: ./kubernetes/apps/kube-system/reloader/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 3m
