---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend-traffic-policy.yaml
  - ./client-traffic-policy.yaml
  - ./envoy-proxy.yaml
  - ./gateway-class.yaml
  - ./gateway.yaml
  - ./http-route.yaml
