---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: coredns-charts
  namespace: flux-system
spec:
  interval: 30m
  timeout: 3m
  url: https://coredns.github.io/helm
