---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: area0
spec:
  events:
    - ping
    - push
  secretRef:
    name: github-webhook-token
  type: github
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      name: area0
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      name: cluster
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      name: cluster-apps
      namespace: flux-system
