---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/endpoints-v1.json
apiVersion: v1
kind: Endpoints
metadata:
  name: &app unifi
  labels:
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
subsets:
  - addresses:
      - ip: "${UNIFI_NETWORK_ADDRESS}"
    ports:
      - name: http
        port: 443
        protocol: TCP
