---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stream
spec:
  chart:
    spec:
      chart: logstream-leader
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: cribl-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
    - kind: ConfigMap
      name: cribl-stream-helm-values
