---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pocket-id-operator
  namespace: &namespace default
spec:
  interval: 1h
  path: ./kubernetes/apps/default/pocket-id/operator
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pocket-id-instance
  namespace: &namespace default
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: pocket-id-operator
      namespace: *namespace
    - name: volsync
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/default/pocket-id/instance
  postBuild:
    substitute:
      APP: pocket-id
      HOSTNAME: id
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false # no flux ks dependents
