# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   meta/main.yml
#   @description    :   metadata for ansible-role-os
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
galaxy_info:
  role_name: os
  author: Chris Burnham
  description: Configure OS baseline

  license: "license Unlicense"

  min_ansible_version: "2.1"

  # https://galaxy.ansible.com/api/v1/platforms/
  platforms:
    - name: Debian
      versions:
        - buster

dependencies:
  - role: os-identification
