---
nameOverride: &app tautulli
env:
  TAUTULLI__PORT: &port 8181
image:
  repository: ghcr.io/onedr0p/tautulli
  tag: 2.12.2@sha256:34072dfc39c1388718a27a33cea7f44fdf89c3ce6108d9c0b5f7b51d40aeb823
ingress:
  main:
    annotations:
      hajimari.io/group: Media
      hajimari.io/icon: mdi:chart-bar
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Accept-Encoding "";
        sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/tautulli/dark.css"></head>';
        sub_filter_once on;
    enabled: true
    hosts:
      - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    ingressClassName: nginx
    tls:
      - hosts:
          - *host
persistence:
  backup:
    enabled: true
    mountPath: /config/backups
    path: "${NAS_NFS_PATH}/backup/app/tautulli"
    server: "${NAS_ADDRESS}"
    type: nfs
  config:
    enabled: true
    existingClaim: tautulli-config-v1
  data:
    enabled: true
    mountPath: /data
    path: "${NAS_NFS_PATH}/apps/tautulli"
    server: "${NAS_ADDRESS}"
    type: nfs
podSecurityContext:
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  runAsGroup: 568
  runAsUser: 568
  supplementalGroups:
    - 100
service:
  main:
    ports:
      http:
        port: *port
