---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-automation
commonLabels:
  app.kubernetes.io/instance: &app overseerr
  app.kubernetes.io/name: *app
configurations:
  - ./kustomize-config.yaml
configMapGenerator:
  - name: overseerr-helm-values
    files:
      - ./values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./persistent-volume-claim.yaml
  - ./helm-release.yaml
