---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-secret
            namespace: external-secrets
            key: token
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      vaults:
        area0: 1
