---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword
spec:
  dataFrom:
    - extract:
        key: 1password
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onepassword-secret
    template:
      data:
        1password-credentials.json: "{{ .OP_CREDENTIALS_JSON }}"
        token: "{{ .OP_CONNECT_TOKEN }}"
