---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  chartRef:
    kind: OCIRepository
    name: onepassword-connect
  interval: 1h
  values:
    controllers:
      onepassword-connect:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          api:
            env:
              OP_BUS_PEERS: localhost:11221
              OP_BUS_PORT: 11220
              OP_HTTP_PORT: &apiPort 8080
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-secret
                    key: 1password-credentials.json
              XDG_DATA_HOME: &configDir /config
            image:
              repository: ghcr.io/1password/connect-api
              tag: 1.8.1@sha256:ac6e9efe4f54cc351393fcb8f01b10e667b08b68ff47ebf6024ff93eae642e5c
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /heartbeat
                    port: *apiPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: *apiPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
            resources: &resources
              limits:
                memory: 64Mi
              requests:
                cpu: 10m
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
          sync:
            env:
              OP_BUS_PEERS: localhost:11220
              OP_BUS_PORT: 11221
              OP_HTTP_PORT: &syncPort 8081
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-secret
                    key: 1password-credentials.json
              XDG_DATA_HOME: *configDir
            image:
              repository: ghcr.io/1password/connect-sync
              tag: 1.8.1@sha256:565e1765aff957379acbb46fab2b2d67380a149d70ef22507d05a5316a100052
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /heartbeat
                    port: *syncPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: *syncPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
            resources: *resources
            securityContext: *securityContext
        strategy: RollingUpdate
    defaultPodOptions:
      securityContext:
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
    persistence:
      config:
        globalMounts:
          - path: *configDir
        type: emptyDir
    service:
      app:
        ports:
          http:
            port: *apiPort
