---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-manager-rules
spec:
  groups:
    - name: cert-manager.rules
      rules:
        - alert: CertManagerAbsent
          annotations:
            description: >-
              New certificates will not be able to be minted, and existing
              ones can't be renewed until cert-manager is back.
            runbook_url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/blob/master/RUNBOOK.md#certmanagerabsent
            summary: >-
              Cert Manager has dissapeared from Prometheus service discovery.
          expr: |-
            absent(up{job="cert-manager"})
          for: 5m
          labels:
            severity: critical

    - name: certificates
      rules:
        - alert: CertManagerCertNotReady
          annotations:
            description:
              This certificate has not been ready to serve traffic for at least 5m.
            runbook_url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/blob/master/RUNBOOK.md#certmanagercertnotready
            summary: >-
              The cert {{ $labels.name }} is not ready to serve traffic.
          expr: |-
            max by (name, exported_namespace, namespace, condition) (certmanager_certificate_ready_status{condition!="True"} == 1)
          for: 5m
          labels:
            severity: critical

        - alert: CertManagerHittingRateLimits
          annotations:
            description: >-
              Depending on the rate limit, cert-manager may be unable to generate certificates for
              up to a week.
            runbook_url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/blob/master/RUNBOOK.md#certmanagerhittingratelimits
            summary: >-
              Cert manager hitting LetsEncrypt rate limits.
          expr: |-
            sum by (host) (rate(certmanager_http_acme_client_request_count{status="429"}[5m])) > 0
          for: 5m
          labels:
            severity: critical
