---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
spec:
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: "${SECRET_DOMAIN/./-}-tls"
