---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-dns-crd-source
  namespace: flux-system
spec:
  # renovate: datasource=github-releases
  url: https://github.com/kubernetes-sigs/external-dns.git
  ref:
    tag: v0.11.0
  ignore: |
    # exclude all
    /*
    # include crds
    !/docs/contributing/crd-source/crd-manifest.yaml
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: external-dns-crd-source
  wait: true
