---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-k10-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 30m
  path: ./kubernetes/apps/kasten-io/k10/config
  prune: false
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: area0
  timeout: 3m
  wait: true
