---
nameOverride: &app radarr
env:
  RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
  RADARR__INSTANCE_NAME: Radarr
  RADARR__LOG_LEVEL: info
  RADARR__PORT: &port 7878
envFrom:
  - secretRef:
      name: *app
image:
  repository: ghcr.io/onedr0p/radarr-develop
  tag: 4.4.1.6926@sha256:f5ffec33b203f9052caf1cf484b1d30f9dc0bc3268c8a439b45e67c3c4dbe5b2
ingress:
  main:
    annotations:
      hajimari.io/group: Media
      hajimari.io/icon: mdi:filmstrip
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Accept-Encoding "";
        sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/radarr/dark.css"></head>';
        sub_filter_once on;
    enabled: true
    hosts:
      - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    ingressClassName: nginx
    tls:
      - hosts:
          - *host
nodeSelector:
  node-role.kubernetes.io/media: "true"
persistence:
  backup:
    enabled: true
    mountPath: /config/Backups
    path: "${NAS_NFS_PATH}/backup/app/radarr"
    server: "${NAS_ADDRESS}"
    type: nfs
  config:
    enabled: true
    existingClaim: radarr-config-v1
  media:
    enabled: true
    mountPath: /media
    path: "${MEDIA_SERVER_NFS_PATH}"
    server: "${MEDIA_SERVER_ADDRESS}"
    type: nfs
podAnnotations:
  secret.reloader.stakater.com/reload: *app
podSecurityContext:
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  runAsGroup: 568
  runAsUser: 568
  supplementalGroups:
    - 100
service:
  main:
    ports:
      http:
        port: *port
