---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-snapshot-controller
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: snapshot-controller
      namespace: kube-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: snapshot-validation-webhook
      namespace: kube-system
  interval: 30m
  path: ./kubernetes/apps/kube-system/snapshot-controller/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: area0
  timeout: 3m
