---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-weave-gitops
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system
  interval: 30m
  path: ./kubernetes/apps/flux-system/weave-gitops/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: area0
  timeout: 3m
