# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_AUTH0_TENANT: ENC[AES256_GCM,data:H9PY55rT1gNvKw==,iv:63sPufRHwZllkDT66Z36OfvAz9YGQEve616Bv7GMEx4=,tag:CBLxdJ7f/JHVOgtOBl7eIQ==,type:str]
    SECRET_AUTH0_K10_CLIENT_ID: ENC[AES256_GCM,data:CUBPfalfSB2bZ3gN8ysLSkL7RnPbOuUky3Pxj8mXeGg=,iv:e6wX0mo4fPZn8jXJ14V9XHSn6gRuPxvbSLMwFwRmAfI=,tag:gvodY24unmwoYEijqYjmkg==,type:str]
    SECRET_AUTH0_K10_CLIENT_SECRET: ENC[AES256_GCM,data:qGH5UwlFqyqwxKnfI4UqmZ+IO2hlJbXdWLp8g6hk/eU3lUiPqAZyxARan5GBR0fyMFQmq6pIGiDBF+YX8OGctA==,iv:O/hsUQ6hbCcc3mpU9MZUK85R3/OekSnzG+PjUuQ5TvU=,tag:4g3f6PEeJ0wL6qVE9WWitw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YeMeCzKyv35mJWdb01+5DvlW7hRhUUReNDoJQCX0,iv:aISjLiomKQgD9bDIU5i3VMmJIFFZs1hjYZ/iPrQUBGI=,tag:y8+2G0PI4DDF4fdlrJiZMg==,type:str]
    SECRET_CLOUDFLARE_GLOBAL_API_KEY: ENC[AES256_GCM,data:wK0aMk+AtWd1ioGxwwMDAiABLlV9G6Zd+5mn0CZ+3dPlFUiZIA==,iv:xAu1KebaJaMTTFf1zelcPhVeRoYFQcUWAM36EFPTM0w=,tag:fQsp5Pz+Dcx9SiY2F9U46g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1LzMV+taqL0W45A=,iv:it674zQq4w3FFrWNWVBCSJcnT8f9oEpfaKWgLsjfiLA=,tag:YaiDDXHYH7KApp34Kgw4Eg==,type:str]
    SECRET_FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:oTiS+Cuz/dCV,iv:ehb3Q1vyPoRzI29cN+3kDA5mkzwG4aoUqwSIFEC7vmg=,tag:9HKk9hOQ4plXvEAWGRy3Aw==,type:str]
    SECRET_FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:Jj+4TA==,iv:d2AyWwyU32aoUCaQgJa8EoliAUN+khb6239/CtG4Ja8=,tag:aSl60NkH4ctg2GLWMmSPBw==,type:str]
    SECRET_KASTEN_ADMIN_EMAIL: ENC[AES256_GCM,data:LP1YLGfW9z+Acsgp2bSuVY3rtLDk+Vfxn3WRmvHS,iv:jSn06zgE6vcsR0dQD3MiEupNFNNFOmwIyRGh4zI6hvI=,tag:d/VHvwbth/TZapPXptGshQ==,type:str]
    SECRET_KASTEN_COMPANY_NAME: ENC[AES256_GCM,data:dAZcpoTUqap6HXYW+9tSRw/G,iv:WWE6cMcPODdqljq6YB5T+tSivI8cjdqatXMzXVwynY0=,tag:9kJ1U2OArwppq5mNWKf4lw==,type:str]
    SECRET_KASTEN_EMAIL: ENC[AES256_GCM,data:qSn1rtge+E4Xf4aEBHkeV2fDTMIrVb/KtJJBI3lqQPZn28hnzsCY/zZ69w==,iv:w1DMmk4ghiO3HYC7rRjq5hJ/7KRxwOQC+rAFxnrfJ7I=,tag:VeKcS7jGe1waiPLFQHywyA==,type:str]
    SECRET_LIDARR_API_KEY: ENC[AES256_GCM,data:4PYpoXyuz8H3nyEaKLmlgLlS9ZmRGu/OIDB4URTomOM=,iv:MThMzrPMgLsFmtENoc6NqnHOV47H+ah5aI+FUqMBfhc=,tag:igG7VcfM3ahKBql40Mj+cA==,type:str]
    SECRET_PROWLARR_API_KEY: ENC[AES256_GCM,data:N+H8SswUJqP4vxVvWrH+l75EnlZbl5ZA0YixpveBFT8=,iv:0ooH15QRPt6tpWZOwyU3ub5qa+DV7WFmL87BboIN5Hs=,tag:CO5fTvONTm6BxpxQw/T1sQ==,type:str]
    SECRET_RADARR_API_KEY: ENC[AES256_GCM,data:+7tuA35KGdO3iEuuzezyieO99CEkzfqvsFcgN8VshBA=,iv:Zg6Xisa4KcU7W5WJpUre5f60/VLxzn7RiOFBABjbb9Q=,tag:GvTjkDdH9V7pLfijToxhXw==,type:str]
    SECRET_SONARR_API_KEY: ENC[AES256_GCM,data:ZfK3bn2n5yF74o5gfaB2UL5v5zOfsqY7/vhxrYQT5LU=,iv:Ag5r15eoHvK6Cu2pH9nIEdqX9K+/UgoaEuPmbMLVV+4=,tag:f0agDFGV7TOWu/y8gorovA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12m8l07w5pjcgz736hh7478k0g7atxgtzrwa42s4umaag6e8hfcgqghkjwe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZmJzbW9QYkhkTXBBRVhH
            UGN5YXZnekpWN0Vrckl4aGlZMVdXb1lQYzE0Clg5WVY0UjJNcjhyVXRSYUg0Y1VR
            VlZQaTBTcnlWTmhOOCtWUUJoenZ5UUkKLS0tIHdGS2ZHRWFncVFkZFBJWDJhMDJQ
            VnBveE11bWdjMmQxeWEzUHJQQ1MySDgKbG7DVNikjK7md41AtfE7UIF9MPQO1pok
            NB7/pyep9ihFzZQj6JDfZI1tgaCjIli0tpjJ+FWCGKdgOdRU6/Ap3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T05:47:43Z"
    mac: ENC[AES256_GCM,data:c3/ayRn/rmnwJEhPVLK/jSNOBktnL13TAkglG1mgQwxQhPRumvr7D31ZLTGd4r3AvvJWOaNGucsi4I1GSpegdk2+s5fR41Oo8wwt9xpdgvKPnnZCaff2lUfk4+RmGYhbOrTNG7tI2pB6o5b3M5GrPpDgm2qscZZtTiSp61mHGbY=,iv:eC7Nj7a7omsWZ6pkz1hMKXajawEE8rh1pXSU23JuGUU=,tag:EhMgo7ZQmZ3WO+dtiikLTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
