---
nameOverride: &app ingress-nginx
controller:
  config:
    client-body-buffer-size: "100M"
    client-body-timeout: 120
    client-header-timeout: 120
    custom-http-errors: 400,401,403,404,500,502,503,504
    enable-brotli: "true"
    forwarded-for-header: "CF-Connecting-IP"
    hsts-max-age: "31449600"
    keep-alive: 120
    keep-alive-requests: 10000
    log-format-escape-json: "true"
    log-format-upstream: >
      {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
      "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
      "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time,
      "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
      "path": "$uri", "request_query": "$args", "request_length": $request_length,
      "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer",
      "http_user_agent": "$http_user_agent"}
    proxy-body-size: "100M"
    ssl-protocols: "TLSv1.3 TLSv1.2"
    use-forwarded-headers: "true"
  extraArgs:
    default-ssl-certificate: |-
      network/${SECRET_DOMAIN/./-}-tls
  extraEnvs:
    - name: TZ
      value: "${CLUSTER_TIME_ZONE}"
  ingressClassResource:
    default: true
  metrics:
    enabled: false
  podAnnotations:
    configmap.reloader.stakater.com/reload: cloudflare-networks
  publishService:
    enabled: true
  replicaCount: 3
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 250Mi
  service:
    externalIPs: ["${SVC_NGINX_ADDRESS}"]
    externalTrafficPolicy: Local
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/component: controller
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
defaultBackend:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: ["ingress-nginx"]
                - key: app.kubernetes.io/component
                  operator: In
                  values: ["default-backend"]
            topologyKey: kubernetes.io/hostname
          weight: 100
  enabled: true
  extraEnvs:
    - name: SHOW_DETAILS
      value: "false"
    - name: TEMPLATE_NAME
      value: lost-in-space
  image:
    repository: ghcr.io/tarampampam/error-pages
    tag: 2.19.0
  replicaCount: 1
