---
nameOverride: &app plex
env:
  PLEX__PORT: &port 32400
image:
  repository: ghcr.io/onedr0p/plex
  tag: 1.30.2.6563-3d4dc0cce@sha256:d0d3e5e75f5ed86843d123cd84bb1f54a0593ec26c908410548862607af880bf
ingress:
  main:
    annotations:
      external-dns.home.arpa/enabled: "true"
      hajimari.io/group: Media
      hajimari.io/icon: mdi:plex
      hajimari.io/url: "https://plex.${SECRET_DOMAIN}/web/index.html"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    enabled: true
    hosts:
      - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    ingressClassName: nginx
    tls:
      - hosts:
          - *host
nodeSelector:
  intel.feature.node.kubernetes.io/gpu: "true"
  node-role.kubernetes.io/media: "true"
  node-role.kubernetes.io/worker: "true"
persistence:
  backup:
    enabled: true
    mountPath: /config/backup
    path: "${NAS_NFS_PATH}/backup/app/plex"
    server: "${NAS_ADDRESS}"
    type: nfs
  config:
    enabled: true
    existingClaim: plex-config-v1
  media:
    enabled: true
    mountPath: /media
    path: "${MEDIA_SERVER_NFS_PATH}"
    server: "${MEDIA_SERVER_ADDRESS}"
    type: nfs
  transcode:
    enabled: true
    type: emptyDir
podSecurityContext:
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  runAsGroup: 568
  runAsUser: 568
  supplementalGroups:
    - 44 # cat /etc/group | grep "video"
    - 107 # cat /etc/group | grep "render"
    - 100
resources:
  limits:
    gpu.intel.com/i915: 1
    memory: 10000Mi
  requests:
    cpu: 100m
    gpu.intel.com/i915: 1
    memory: 2000Mi
service:
  main:
    annotations:
      metallb.universe.tf/allow-shared-ip: *app
    externalTrafficPolicy: Local
    loadBalancerIP: "${SVC_PLEX_ADDRESS}"
    ports:
      http:
        port: *port
    type: LoadBalancer
