# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   inventory/group_vars/all/global.yml
#   @description    :   global variables for the site
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
# --------------------------------------------------------------------------------------------------
# ansible settings
# --------------------------------------------------------------------------------------------------
# -- (bool) force privilege escalation
ansible_become: true

# -- (bool) determines whether or not to use SSH pipelining
ansible_ssh_pipelining: false

# -- (str) private key file used by ansible ssh
ansible_ssh_private_key_file: ~/.ssh/id_rsa_kane

# -- (str) public key file used by ansible ssh
ansible_ssh_public_key_file: ~/.ssh/id_rsa_kane.pub

# -- (str) the user name to use when connecting to the host
ansible_user: kane
# ==================================================================================================


# --------------------------------------------------------------------------------------------------
# time settings
# --------------------------------------------------------------------------------------------------
# -- (str) timezone for the site
timezone: "America/Chicago"
# ==================================================================================================
