---
# TODO: yaml-language-server: $schema=
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: kube-memory-overcommit
spec:
  matchers:
    - name: alertname
      value: KubeMemoryOvercommit
