# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   requirements.yml
#   @description    :   ansible requirements
#   @usage          :   ansible-galaxy install -p roles-galaxy -r requirements.yml --force
#                   :   ansible-galaxy collection install -p collections -r requirements.yml --upgrade
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
# --------------------------------------------------------------------------------------------------
# roles
# --------------------------------------------------------------------------------------------------
roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: robertdebock.bootstrap
    version: 6.0.3
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.1
# ==================================================================================================

# --------------------------------------------------------------------------------------------------
# collections
# --------------------------------------------------------------------------------------------------
collections:
  - name: community.general
    version: 6.4.0
  - name: community.sops
    version: 1.6.1
  - name: kubernetes.core
    version: 2.4.0
# ==================================================================================================
