# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   requirements.yml
#   @description    :   ansible requirements
#   @usage          :   ansible-galaxy install -p roles-galaxy -r requirements.yml --force
#                   :   ansible-galaxy collection install -p collections -r requirements.yml --upgrade
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
# --------------------------------------------------------------------------------------------------
# roles
# --------------------------------------------------------------------------------------------------
roles:
  - src: robertdebock.bootstrap
    version: 6.0.3
  - src: xanmanning.k3s
    version: v3.1.1
  - src: https://github.com/mrlesmithjr/ansible-zfs.git
    scm: git
    name: mrlesmithjr.zfs
    version: b80e84d6938eb7730faeffc7ff7d8aa06ad5bef7
# ==================================================================================================

# --------------------------------------------------------------------------------------------------
# collections
# --------------------------------------------------------------------------------------------------
collections:
  - name: community.sops
    version: 1.2.1
  - name: kubernetes.core
    version: 2.3.0
# ==================================================================================================
