---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: download
commonLabels:
  app.kubernetes.io/instance: &app sabnzbd
  app.kubernetes.io/name: *app
configurations:
  - ./kustomize-config.yaml
configMapGenerator:
  - name: sabnzbd-helm-values
    files:
      - ./values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./secret.sops.yaml
  - ./persistent-volume-claim.yaml
  - ./helm-release.yaml
