---
nameOverride: &app recyclarr
args: ["sync"]
command: ["/app/recyclarr/recyclarr"]
controller:
  cronjob:
    schedule: "@daily"
    ttlSecondsAfterFinished: 86400
  type: cronjob
envFrom:
  - secretRef:
      name: radarr
  - secretRef:
      name: sonarr
image:
  repository: ghcr.io/recyclarr/recyclarr
  tag: edge@sha256:5d93d767a847563f056812a1631d277783473188eee4bf5b47023d00b5f60770
persistence:
  config:
    defaultMode: 0775
    enabled: true
    mountPath: /config/recyclarr.yml
    name: recyclarr-configmap
    readOnly: true
    subPath: recyclarr.yml
    type: configMap
restartPolicy: OnFailure
service:
  main:
    enabled: false
