---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kyverno-cluster-policies
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-kyverno
  interval: 30m
  path: ./kubernetes/apps/kyverno/cluster-policies/policies
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: area0
  timeout: 3m
  wait: true
