---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-k8s-gateway
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-metallb
    - name: cluster-apps-metallb-config
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: k8s-gateway
      namespace: network
  interval: 30m
  path: ./kubernetes/apps/networking/k8s-gateway/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  timeout: 3m
