---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: pocket-id
        property: MEALIE_OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: pocket-id
        property: MEALIE_OIDC_CLIENT_SECRET
    - secretKey: OIDC_CONFIGURATION_URL
      remoteRef:
        key: pocket-id
        property: MEALIE_OIDC_CONFIGURATION_URL
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie-secret
    template:
      data:
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_CONFIGURATION_URL: "{{ .OIDC_CONFIGURATION_URL }}"
