---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: mealie-admins
spec:
  friendlyName: Mealie Admins
  name: mealie_admins
  users:
    usernames:
      - cburnham
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: mealie-users
spec:
  friendlyName: Mealie Users
  name: mealie_users
  users:
    usernames:
      - cburnham
      - jburnham
