---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: mealie
spec:
  allowedUserGroups:
    - name: mealie-admins
    - name: mealie-users
  callbackUrls:
    - "https://${HOSTNAME:=${APP}}.${SECRET_DOMAIN}/"
    - "https://${HOSTNAME:=${APP}}.${SECRET_DOMAIN}/login"
    - "https://${HOSTNAME:=${APP}}.${SECRET_DOMAIN}?direct=1"
  launchUrl: "https://${HOSTNAME:=${APP}}.${SECRET_DOMAIN}"
  logoutCallbackUrls:
    - "https://${HOSTNAME:=${APP}}.${SECRET_DOMAIN}"
  pkceEnabled: true
