---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  dataFrom:
    - extract:
        key: pocket-id
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pocket-id-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .POCKET_ID_ENCRYPTION_KEY }}"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-admin
spec:
  dataFrom:
    - extract:
        key: pocket-id-admin
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pocket-id-admin-secret
    template:
      data:
        username: "{{ .username }}"
        firstName: "{{ .firstName }}"
        email: "{{ .email }}"
        displayName: "{{ .displayName }}"
