---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagekey_v1alpha1.json
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: pocket-id-garage-key
spec:
  bucketPermissions:
    - bucketRef: pocket-id-files
      read: true
      write: true
  clusterRef:
    name: garage-gateway
    namespace: storage
