---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagebucket_v1alpha1.json
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: pocket-id-files
spec:
  clusterRef:
    name: garage-gateway
    namespace: storage
  quotas:
    maxSize: 8Gi
