---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pocket-id
spec:
  hostnames:
    - "${HOSTNAME:=${APP}}.${SECRET_DOMAIN}"
  parentRefs:
    # - name: envoy-external
    #   namespace: network
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: pocket-id
          namespace: default
          port: 1411
