---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secret.yaml
  - ./garage-bucket.yaml
  - ./garage-key.yaml
  - ./http-route.yaml
  - ./pocket-id-instance.yaml
  - ./pocket-id-user-group.yaml
  - ./pocket-id-user.yaml
