---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketiduser_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUser
metadata:
  name: admin
spec:
  admin: true
  locale: en
  userInfoSecretRef:
    name: pocket-id-admin-secret
