---
# TODO: yaml-language-server: $schema=
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUser
metadata:
  name: admin
spec:
  admin: true
  locale: en
  userInfoSecretRef:
    name: pocket-id-admin-secret
