---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
commonLabels:
  app.kubernetes.io/instance: &app external-dns
  app.kubernetes.io/name: *app
configurations:
  - ./kustomize-config.yaml
configMapGenerator:
  - name: external-dns-helm-values
    files:
      - ./values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./secret.sops.yaml
  - ./helm-release.yaml
