---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dockerhub-rules
spec:
  groups:
    - name: dockerhub.rules
      rules:
        - alert: DockerHubRateLimitRisk
          annotations:
            description: >-
              Kubernetes cluster is at risk of being rate limited by DockerHub.
            # runbook_url:
            summary: >-
              There are {{ $value }} containers pulling from Dockerhub. This may lead to rate limiting.
          expr: |-
            count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          labels:
            severity: critical
