---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 6.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  dependsOn:
    - name: coredns
      namespace: network
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 5m
  upgrade:
    remediation:
      retries: 3
  values:
    crd:
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
    coredns:
      etcdEndpoints: "https://${K3S_CONTROL_NODE_1_ADDRESS}:2379,https://${K3S_CONTROL_NODE_2_ADDRESS}:2379,https://${K3S_CONTROL_NODE_3_ADDRESS}:2379"
      etcdTLS:
        enabled: true
        secretName: coredns-etcd
    domainFilters:
      - "${SECRET_DOMAIN}"
    interval: 1m
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    nameOverride: internal-dns
    policy: sync
    provider: coredns
    sources:
      - crd
      - service
      - ingress
    txtPrefix: "k8s."
