---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-instance-rules
spec:
  groups:
    - name: flux-instance.rules
      rules:
        - alert: FluxInstanceAbsent
          annotations:
            description: >-
              The flux_instance_info metric for the Flux instance in namespace
              {{ $labels.exported_namespace }} is not available.
            # runbook_url:
            summary: >-
              Flux instance metric is missing.
          expr: |-
            absent(flux_instance_info{exported_namespace="flux-system", name="flux"})
          for: 5m
          labels:
            severity: critical

        - alert: FluxInstanceNotReady
          annotations:
            description: >-
              The Flux instance in namespace {{ $labels.exported_namespace }} is not ready.
              Reason: {{ $labels.reason }}.
            # runbook_url:
            summary: >-
              Flux instance {{ $labels.name }} is not ready.
          expr: |-
            flux_instance_info{exported_namespace="flux-system", name="flux", ready!="True"}
          for: 5m
          labels:
            severity: critical

        - alert: HelmReleaseReconciliationFailure
          annotations:
            description: >-
              HelmRelease {{ $labels.name }} in {{ $labels.exported_namespace }} is not ready.
              Reason: {{ $labels.reason }}.
            # runbook_url:
            summary: >-
              HelmRelease {{ $labels.name }} is not ready.
          expr: |-
            gotk_resource_info{customresource_kind="HelmRelease", ready!="True"} == 1
          for: 5m
          labels:
            severity: critical

        - alert: KustomizationReconciliationFailure
          annotations:
            description: >-
              The Kustomization {{ $labels.name }} in {{ $labels.exported_namespace }} is not ready.
              Reason: {{ $labels.reason }}.
            # runbook_url:
            summary: >-
              Kustomization {{ $labels.name }} is not ready.
          expr: |-
            gotk_resource_info{customresource_kind="Kustomization", ready!="True"} == 1
          for: 5m
          labels:
            severity: critical
