---
name: MegaLinter

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_PRIVATE_KEY }}"
      - name: Run MegaLinter
        env:
          ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .github/linters/.ansible-lint
          ANSIBLE_DIRECTORY: ansible
          ENABLE_LINTERS: |-
            ${{
              join(
                fromJSON('
                  [
                    "ACTION_ACTIONLINT",
                    "ANSIBLE_ANSIBLE_LINT",
                    "BASH_SHELLCHECK",
                    "COPYPASTE_JSCPD",
                    "CREDENTIALS_SECRETLINT",
                    "DOCKERFILE_HADOLINT",
                    "ENV_DOTENV_LINTER",
                    "GIT_GIT_DIFF",
                    "JSON_JSONLINT",
                    "KUBERNETES_KUBEVAL",
                    "MARKDOWN_MARKDOWNLINT",
                    "TERRAFORM_TFLINT",
                    "YAML_YAMLLINT"
                  ]
                '),
                ','
              )
            }}
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          KUBERNETES_DIRECTORY: k8s
          KUBERNETES_KUBEVAL_ARGUMENTS: --ignore-missing-schemas
          KUBERNETES_KUBEVAL_FILTER_REGEX_INCLUDE: "(k8s/cluster)"
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .github/linters/.markdownlint.yaml
          PRINT_ALPACA: false
          TERRAFORM_TFLINT_CONFIG_FILE: .github/linters/.tflint.hcl
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          YAML_YAMLLINT_CONFIG_FILE: .github/linters/.yamllint.yaml
        uses: megalinter/megalinter/flavors/terraform@v5
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log
