---
name: Publish Cloudflare Networks

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  DEFAULT_CLOUDFLARE_NETWORKS_FILE: |-
    kubernetes/apps/network/ingress-nginx/app/cloudflare-networks.txt

jobs:
  cloudflare-networks:
    name: Publish Cloudflare Networks
    runs-on: ubuntu-latest
    steps:

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_PRIVATE_KEY }}"

      - name: Check out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Get Cloudflare networks
        run: |
          cloudflare_networks_file=$(find . -name "cloudflare-networks.txt" -print -quit)
          if [[ -f "${cloudflare_networks_file}" ]]; then
              npx zx ./.github/scripts/cloudflareNetworks.mjs > "${cloudflare_networks_file}"
              exit 0
          fi
          npx zx ./.github/scripts/cloudflareNetworks.mjs > ${{ env.DEFAULT_CLOUDFLARE_NETWORKS_FILE }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          body: |
            Update Cloudflare networks configmap from https://api.cloudflare.com/client/v4/ips
          branch: github-action/update-cloudflare-networks
          commit-message: "chore(github-action): update cloudflare networks"
          delete-branch: true
          labels: |
            renovate/github-action
          signoff: true
          title: "chore(github-action): update cloudflare networks"
          token: "${{ steps.generate-token.outputs.token }}"
