# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @file           :   ansible/inventory/host_vars/localhost.yml
#   @description    :   host variables
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
# --------------------------------------------------------------------------------------------------
# ansible settings
# --------------------------------------------------------------------------------------------------
ansible_become: false
ansible_connection: local
# ==================================================================================================
