# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name smartctl-exporter
spec:
  metricsPath: /metrics
  relabelings:
    - action: replace
      replacement: *name
      targetLabel: job
  staticConfigs:
    - targets:
        - "${NAS_ADDRESS}:9633"
